--- #YAML:1.0
name:               Desktop-Notify
version:            0.02
abstract:           Communicate with the Desktop Notifications framework
author:
    - Stephen Cavilia <sac@atomicradi.us>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:  0
    Net::DBus:        0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
